### DISCUSSION TITLE
OpenAI og HA Aula har reddet hverdagen

### DISCUSSION THREAD

**Discussion by CasperJ** [scaarup/aula#188] [Show and tell]
Hej,

Først og fremmest, 1000 tak for det fantastiske arbejde I har lavet med at få Aula ind i HA 👊

Vores lærer i vores datters klasse skriver lange ugeplaner om alverdens ting. Mange af tingene glemmer vi at huske på selve dagen og så kommer ungen afsted uden turtaske eller hvad det nu kunne være.

Jeg har kombineret Aula ugeplan sensoren med OpenAI conversation og kan nu lave et meningsfyldt resumé per dag.
Her er min automation:

```yaml
alias: Aula XXXs huskeliste
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.skolen_pa_islands_brygge_xxx
    attribute: ugeplan
conditions: []
actions:
  - variables:
      summary_response: ""
  - action: conversation.process
    metadata: {}
    data:
      text: >
        Givet følgende ugeplan for mit barns skole, list de dage hvor jeg som
        forældre skal huske mit barn på at have noget med på dagen. F.eks.
        gymnastiktøj, turtaske, lektier, tøj, osv.


        Outputformatet skal være et JSON array med ét objekt for hver dag.
        Formatet for objektet er:

        {
          "date": "YYYY-MM-DD",
          "message": "dét, der skal huskes"
        }


        returner KUN json og intet andet.


        Ugeplan:

        {{ state_attr("sensor.skolen_pa_islands_brygge_xxx", "ugeplan") }}
      agent_id: conversation.chatgpt
    response_variable: summary_response
  - variables:
      huskeliste: >-
        {{ summary_response.response.speech.plain.speech | string |
        regex_replace(find="\s*```json\s*", replace='') |
        regex_replace(find="\s*```\s*", replace='')}}
  - repeat:
      count: "{{ huskeliste | count }}"
      sequence:
        - action: notify.persistent_notification
          metadata: {}
          data:
            title: Husk!
            message: >-
              [{{ huskeliste[repeat.index - 1].date }}]: {{
              huskeliste[repeat.index - 1].message }}
mode: single
```

Resultatet er en notifikation per dag der skal huskes noget.
Denne uge ser således ud:

![{860597AF-193F-41ED-9EA4-EAB9C2C4FB6F}](https://github.com/user-attachments/assets/081c9925-a9c6-462e-8792-f681d0d4ceed)

Næste skridt må være at først sende notifikation på selve dagen til den korrekte unges iPad + min egen telefon :)

Endnu engang tak for denne brugebare integration

**Comment by scaarup** [comment]
Hej @CasperJ 

Det er da super fedt det der :)

Jeg har ikke selv rodet med OpenAI Conversation og HA endnu. Men det bliver jeg da nok nødt til at få prøvet nu. Tænker også det kunne være brugbart at få AI til at gennemgå de mange beskeder, der dukker op og filtrere de 90% ligegyldige fra.

Du må gerne ligge din automation mv. ind i wiki'en her, hvis du gider.
👍🏻

**Comment by scaarup** [comment]
Hermed et lille eksempel, med @CasperJ's automation som stærk inspiration, på hvordan vi kan gennemgå ulæste beskeder og summere dem op:

```yaml
description: ""
triggers: []
conditions: []
actions:
  - variables:
      aula_messages: ""
      summary_response: ""
  - action: aula.api_call
    data:
      uri: >-
        ?method=messaging.getThreads&sortOn=date&orderDirection=desc&page=0&filterOn=unread
    response_variable: aula_messages
  - action: conversation.process
    metadata: {}
    data:
      text: >
        Herunder er der beskeder fra forældre og lærere fra mit barns skole. Du
        skal gennemgå beskederne og fortælle mig om der er noget jeg skal huske.

        Outputformatet skal være et JSON object Formatet for objektet er:

        {
          "message": "dét, der skal huskes"
        }

        returner KUN json og intet andet.

        Beskeder:

        {{ aula_messages }}
      agent_id: conversation.chatgpt
    response_variable: summary_response
  - variables:
      huskeliste: >-
        {{ summary_response.response.speech.plain.speech | string |
        regex_replace(find="\s*```json\s*", replace='') |
        regex_replace(find="\s*```\s*", replace='')}}
  - action: notify.mobile_app_iphone11scaa
    metadata: {}
    data:
      title: Besked fra Aula
      message: "{{ huskeliste.message }}"
mode: single
```

**Reply by plaiddk** [reply]
Mega fedt lavet! Men det er som om jeg også får resumer fra ikke ulæste beskeder? Jeg fik bl.a. et resume fra en besked i 2022 :) 

Kan man se noget dokumentation om det api kald der laves? Måske den skal finjusteres. Men fed feature!

**Comment by Fumper1** [comment]
Sjovt som man kan løse ting på forskellige måder, jeg har løst det ved at dele ugeplanen op i dage, og så har jeg en checkliste ungerne skal kigge på og om eftermiddag/aften er der et punkt til at kigge på ugeplanen, om morgenen indtil 9 viser den ugeplanen for idag, og herefter for imorgen, fredag eftermiddag til søndag viser den hele næste uge. 
Checkliste:
![billede](https://github.com/user-attachments/assets/125003c4-a911-431d-aac0-c98169a69def)

Ugeplan

![billede](https://github.com/user-attachments/assets/20e2bc84-6bef-4220-b3fe-b48fd1b60616)

lige nu er f.eks. idræt og bibliotek hardcodet, og det giver lidt problemer når de flytter rundt, så næste skridt bliver at gøre det dynamisk, og kun have "husk biblioteksbøger" på den dag hvor det er nævnt i ugeplanen, og "pakke idrætstøj" på den dag hvor det står på skemaet hvis ikke det er nævnt i ugeplanen at det skal springes over. Jeg har allerede sat op så "husk solcreme" kommer på når uv-indekset for dagen når over 3, men det hele er startet med Aula integrationen, så også tak herfra.

**Reply by Andiandersen** [reply]
Hej @Fumper1  hvordan har du lavet selve checklisten? med knapperne?

**Reply by thebonden** [reply]
jeg følger også lige med her

**Comment by scaarup** [comment]
@Fumper1 : Lige den med at pakke idrætstøj (og pakke det ud igen!), har jeg løst således:

```yaml
alias: Husk idrætstøj
description: ""
mode: single
triggers:
  - event: start
    offset: "-24:0:0"
    entity_id: calendar.skoleskema_rasmus_hallberg_friis_aarup
    id: rasmus_idrat_todo
    trigger: calendar
  - event: start
    offset: "1:0:0"
    entity_id: calendar.skoleskema_rasmus_hallberg_friis_aarup
    id: rasmus_idrat_pakke_ud
    trigger: calendar
conditions:
  - condition: template
    value_template: "{{ 'Idræt' in trigger.calendar_event.summary }}"
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - rasmus_idrat_todo
          - condition: template
            value_template: "{{ not \"Pak idrætstøj\" in states.sensor.rasmus_todos.state }}"
        sequence:
          - data:
              item: Pak idrætstøj
            target:
              entity_id: todo.rasmus
            action: todo.add_item
  - choose:
      - conditions:
          - condition: trigger
            id:
              - rasmus_idrat_pakke_ud
          - condition: template
            value_template: "{{ not \"Tøm idrætstaske\" in states.sensor.rasmus_todos.state }}"
        sequence:
          - data:
              item: Tøm idrætstaske
            target:
              entity_id: todo.rasmus
            action: todo.add_item

```

Men det ligner du bruger nogle switch entities some en slags "todo" ? Hvorfor ikke bruge todo lister? De er meget mere dynamiske. Jeg bruger dem til min ungers pligter og så krydser de selv af. Der er ikke noget internet til gamer computeren før alt er checket af :)
