### DISCUSSION TITLE
Question to example on "Entities card with additional information"

### DISCUSSION THREAD

**Discussion by sunebuhl** [scaarup/aula#94] [Q&A] [answered]
Thanks for the great work on this. 

I'm trying to follow the example on "Entities card with additional information" showing times from SFO. 

I've changed all the sensors to match my entities but I don't see any output.

Does the input boolen need to be defined somewhere else in HA?

```
  - type: conditional
    conditions:
      - entity: input_boolean.morn_unger
        state: 'on'
```
