### ISSUE TITLE
integration no longer provides entities

### ISSUE THREAD

**Issue by DIYtechie** [scaarup/aula#129]
**Describe the bug or problem (In Danish is OK)**

**Please answer the following**
- Version of integration: v0.1.35
- Version of Home Assistant: 2024.1.3 (Home Assistant OS 11.4)
- [x] I have more than one child
- [x] My children are attending different schools / institutions

**REQUIRED! Provide debug log from the integration**
- Enable by adding the following to your configuration.yaml:
```
logger:
  default: info
  logs:
    custom_components.aula: debug
```
- Restart Home Assistant
- Capture all log lines (from the integration only), save it to a file and attach it to here.
