### ISSUE TITLE
No devices or entities when setting up

### ISSUE THREAD

**Issue by kjjordans** [scaarup/aula#187]
**Describe the bug or problem (In Danish is OK)**
I have tried to set up the integration. 
I have tried to set up the integration with both ticked
- Add school schedules as calendar entities?
- Add ugeplaner as sensor attributes?

If i set up the integration without any of the options ticked, I get one entity with a message from Aula

**Please answer the following**
- Version of integration: 0.1.40
- Version of Home Assistant:  2024.9.1
- [ ] I have more than one child - I am only setting up one child from one school to begin with. 
- [ ] My children are attending different schools / institutions - I am only setting up one child from one school to begin with. 

**REQUIRED! Provide debug log from the integration**
- Enable by adding the following to your configuration.yaml:
```
logger:
  default: info
  logs:
    custom_components.aula: debug
[HomeAssistantAula.log](https://github.com/user-attachments/files/17133936/HomeAssistantAula.log)

```
- Restart Home Assistant
- Capture all log lines (from the integration only), save it to a file and attach it to here.
[HomeAssistantAula.log](https://github.com/user-attachments/files/17133936/HomeAssistantAula.log)
